### ISSUE TITLE
将图片一直缩小的话会出异常

### ISSUE THREAD

**Issue by daidaijie** [ongakuer/PhotoDraweeView#23]
Process: com.example.daidaijie.syllabusapplication, PID: 10619
                                                   java.lang.IllegalArgumentException: pointerIndex out of range
                                                       at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                       at android.view.MotionEvent.getX(MotionEvent.java:1983)
                                                       at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
                                                       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
                                                       at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
                                                       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1992)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2095)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2398)
                                                       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1739)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2783)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2359)
                                                       at android.view.View.dispatchPointerEvent(View.java:8698)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4525)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4383)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3919)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3972)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3938)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4048)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3946)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4105)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3919)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3972)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3938)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3946)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3919)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6340)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6296)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6249)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6502)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:148)
                                                       at android.os.Looper.loop(Looper.java:151)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)

**Comment by ongakuer** [comment]
是在viewpager内使用吗？

**Comment by daidaijie** [comment]
@ongakuer 是的，有时候放大也会出现这个问题

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView/issues/1

你需要使用 sample 中的 [MultiTouchViewPager]( https://github.com/ongakuer/PhotoDraweeView/blob/master/sample/src/main/java/me/relex/photodraweeview/sample/MultiTouchViewPager.java) 来处理。

**Comment by daidaijie** [comment]
@ongakuer 好的，我试试，感谢你开源了这么棒的控件
