### ISSUE TITLE
This component doesn't save from such kind of exception

### ISSUE THREAD

**Issue by Messme** [ongakuer/PhotoDraweeView#25]
E/ViewDragHelper: Ignoring pointerId=1 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.

Process: com.messme, PID: 3554
                                                          java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                              at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
                                                              at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
                                                              at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1434)
                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)

and so on.
Phone Samsung Galasy S4 I9500, OS Android 5.1.1

**Comment by ongakuer** [comment]
https://github.com/chrisbanes/PhotoView#issues-with-viewgroups
