### ISSUE TITLE
App crash when zoom out to minimum level

### ISSUE THREAD

**Issue by pinvisible** [ongakuer/PhotoDraweeView#28]
Thanks for really nice work. But i am getting one issue. When we zoom out image from original level, then it get crashed. It works good with Zoom-In. Can you please suggest me?

**Comment by ongakuer** [comment]
Need details. Any crash log?

**Comment by CloudWoo** [comment]
Same Problem, here is the log
java.lang.IllegalArgumentException: pointerIndex out of range

**Comment by CloudWoo** [comment]
I just fix the problem， just overwrite the viewpager

`public class ScaleViewPager extends ViewPager {
    public ScaleViewPager(Context context) {
        super(context);
    }

    public ScaleViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        try{
            super.onTouchEvent(ev);
        } catch(IllegalArgumentException ex) {

        }
        return false;
    }


    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            super.onInterceptTouchEvent(ev);
        }catch (IllegalArgumentException ex){

        }
        return false;
    }
}
`

**Comment by CloudWoo** [comment]
`public class ScaleViewPager extends ViewPager {
    public ScaleViewPager(Context context) {
        super(context);
    }

    public ScaleViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        try{
            super.onTouchEvent(ev);
        } catch(IllegalArgumentException ex) {

        }
        return false;
    }


    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            super.onInterceptTouchEvent(ev);
        }catch (IllegalArgumentException ex){

        }
        return false;
    }
}
`

**Comment by CloudWoo** [comment]
I just fix the problem, overwrite the viewpager. By the way, thanks for  ongakuer`s great work.
```
public class ScaleViewPager extends ViewPager {
    public ScaleViewPager(Context context) {
        super(context);
    }

    public ScaleViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        try{
            super.onTouchEvent(ev);
        } catch(IllegalArgumentException ex) {

        }
        return false;
    }


    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            super.onInterceptTouchEvent(ev);
        }catch (IllegalArgumentException ex){

        }
        return false;
    }
}
```

**Comment by CloudWoo** [comment]
Just fix the problem, here is my crash log. you should overwrite the view that crash because  of the IllegalArgumentException.
```
 java.lang.IllegalArgumentException: pointerIndex out of range
                                                                             at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                             at android.view.MotionEvent.getX(MotionEvent.java:2111)
                                                                             at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2064)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2310)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
```




```
public class ScaleViewPager extends ViewPager {
    public ScaleViewPager(Context context) {
        super(context);
    }

    public ScaleViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        try{
            super.onTouchEvent(ev);
        } catch(IllegalArgumentException ex) {
            return false;
        }
        return super.onTouchEvent(ev);
    }


    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            super.onInterceptTouchEvent(ev);
        }catch (IllegalArgumentException ex){
            return false;
        }
        return super.onInterceptTouchEvent(ev);
    }
}
```

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView#issues-with-viewgroups

https://github.com/ongakuer/PhotoDraweeView/blob/master/sample/src/main/java/me/relex/photodraweeview/sample/MultiTouchViewPager.java
