### ISSUE TITLE
哥们狂报这个 异常！！！

### ISSUE THREAD

**Issue by xiedong** [ongakuer/PhotoDraweeView#38]
10-18 10:46:02.051 25780-25780/com.android.lft E/InputEventReceiver: Exception dispatching input event.
10-18 10:46:02.053 25780-25780/com.android.lft E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
10-18 10:46:02.058 25780-25780/com.android.lft E/MessageQueue-JNI: java.lang.IllegalArgumentException: pointerIndex out of range
                                                                       at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                       at android.view.MotionEvent.getX(MotionEvent.java:2089)
                                                                       at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
                                                                       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
                                                                       at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
                                                                       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1987)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2109)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2820)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                       at android.view.View.dispatchPointerEvent(View.java:9526)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4262)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4128)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3814)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
                                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3871)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5954)
                                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5928)
                                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5889)
                                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6057)
                                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
10-18 10:46:02.069 25780-25780/com.android.lft E/Throwable: java.lang.IllegalArgumentException: pointerIndex out of range

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView/issues/35

**Comment by xiedong** [comment]
小米NOTE MIUI 8.0 稳定版 8.0.3.0（MXECNDG） 貌似是 触控的一个异常没有解决

**Comment by xiedong** [comment]
O.O 为什么要关掉那  必蹦的 BUG

**Comment by ongakuer** [comment]
重复Bug，前面一个给了相关解决方案了。

**Comment by xiedong** [comment]
好的 我看看
