### ISSUE TITLE
缩小到最小会崩溃

### ISSUE THREAD

**Issue by umeitime** [ongakuer/PhotoDraweeView#47]
11-13 15:27:22.817 17643-17643/me.umeitimes.act.www E/MotionEvent-JNI: validatePointerIndex pointerIndex:-1, pointerCount:1
11-13 15:27:22.818 17643-17643/me.umeitimes.act.www E/InputEventReceiver: Exception dispatching input event.
11-13 15:27:22.901 17643-17713/me.umeitimes.act.www E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
11-13 15:27:22.946 17643-17643/me.umeitimes.act.www E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: me.umeitimes.act.www, PID: 17643
                                                                      java.lang.IllegalArgumentException: pointerIndex out of range
                                                                          at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                          at android.view.MotionEvent.getX(MotionEvent.java:2014)
                                                                          at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2096)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2000)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2539)
                                                                          at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1807)
                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:2823)
                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2496)
                                                                          at android.view.View.dispatchPointerEvent(View.java:8874)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4774)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4606)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4135)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4101)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4238)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4109)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4295)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4135)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4101)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4109)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4082)
                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6593)
                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6567)
                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6520)
                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6773)
                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                          at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                          at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                          at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6711)
                                                                          at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6799)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:570)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                      	at android.os.Handler.dispatchMessage(Hand

**Comment by ongakuer** [comment]
#35
