### ISSUE TITLE
PhotoDraweeView 在ViewPage内多次缩小手势会奔溃

### ISSUE THREAD

**Issue by 88567free** [ongakuer/PhotoDraweeView#48]
java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1
                                                                       at android.view.MotionEvent.nativeGetAxisValue(Native Method)
                                                                       at android.view.MotionEvent.getX(MotionEvent.java:2072)
                                                                       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2064)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
有什么解决方法吗

**Comment by ongakuer** [comment]
#35

**Comment by 88567free** [comment]
谢谢
