### ISSUE TITLE
放大缩小崩溃问题

### ISSUE THREAD

**Issue by ray0807** [ongakuer/PhotoDraweeView#53]
在频繁放大缩小图片时会出现奔溃，特别是刚开始加载图片时（已经修改过了viewpager）

02-04 11:43:22.680 5070-5070/? E/ViewDragHelper: Ignoring pointerId=1 because ACTION_DOWN was not received for this pointer before ACTION_MOVE. It likely happened because  ViewDragHelper did not receive all the events in the event stream.
02-04 11:43:22.680 5070-5070/? E/InputEventReceiver: Exception dispatching input event.
02-04 11:43:23.000 5070-5070/? E/Tinker.SampleUncaughtExHandler: uncaughtException:length=1; index=1
02-04 11:43:23.000 5070-5070/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                             at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
                                                             at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
                                                             at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1434)
                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                             at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
                                                             at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
                                                             at android.view.View.dispatchPointerEvent(View.java:10228)
                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5350)
                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5186)
                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4679)
                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4645)
                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4787)
                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4653)
                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4844)
                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4679)
                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4645)
                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4653)
                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7323)
                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7201)
                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7162)
                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7433)
                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                             at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                             at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                             at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7397)
                                                             at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7460)
                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                             at android.view.Choreographer.doFrame(Choreographer.java:625)
                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:158)
                                                             at android.app.ActivityThread.main(ActivityThread.java:7233)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView/issues/35

**Comment by ray0807** [comment]
@ongakuer  我已经按照上面的方法改过了  一样有问题

**Comment by ongakuer** [comment]
不只是 ViewPager 。crashlog 显示由于 DrawerLayout  导致的。

https://github.com/chrisbanes/PhotoView#issues-with-viewgroups
