### ISSUE TITLE
有两个问题请教下

### ISSUE THREAD

**Issue by CrazySongCN** [ongakuer/PhotoDraweeView#63]
1.缩放时会闪退，日志如下 
E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.itcode.reader, PID: 11737
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:2014)
at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2064)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1962)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2553)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1755)
at android.app.Activity.dispatchTouchEvent(Activity.java:2850)
at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2507)
at android.view.View.dispatchPointerEvent(View.java:8686)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4401)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4263)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3817)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3870)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3836)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3953)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3844)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4010)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3817)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3870)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3836)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3844)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3817)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6129)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6074)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6045)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6304)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:122)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1117)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

2.setScaleType无效
![default](https://user-images.githubusercontent.com/17328866/27065185-5b19787e-502e-11e7-8588-8225ee13ff34.png)

我想让图片宽度满屏幕显示

**Comment by CrazySongCN** [comment]
第一个问题看了close的issue解决了 第二个等更新是吗？

**Comment by ongakuer** [comment]
1.  请查看 https://github.com/chrisbanes/PhotoView#issues-with-viewgroups
2. 不支持 setScaleType

**Comment by CrazySongCN** [comment]
那想实现填满屏幕有合适的方法吗？谢谢了

**Comment by ongakuer** [comment]
可以看看这个 https://github.com/ongakuer/PhotoDraweeView/issues/41
