### ISSUE TITLE
多点触摸放大缩小时崩溃

### ISSUE THREAD

**Issue by main1230** [ongakuer/PhotoDraweeView#70]
多点触摸频繁的放大缩小时发生崩溃
java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:2122)
	at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1916)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
	at android.view.View.dispatchPointerEvent(View.java:10232)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6750)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6831)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
	at android.view.Choreographer.doCallbacks(Choreographer.java:735)
	at android.view.Choreographer.doFrame(Choreographer.java:661)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by ongakuer** [comment]
https://github.com/ongakuer/PhotoDraweeView/issues/35

**Comment by main1230** [comment]
OK
